stages:
  - manual
  - release
  - build
  - dev
  - stg
  - deploy
  - upload
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # This is condition for trigger build manual proto npm package
    - if: '$PATH_MANUAL != ""'
    
include: 
- local: '.gitlab-ci/*.gitlab-ci.yml'