stages:
  - release
  - build
  - upload

variables:
  SCRIPT_DIR: $CI_PROJECT_DIR/.gitlab-ci/scripts
  DYNAMODB_TABLE: cicd-deploy-state

# Run when open merge request to master & merged to master
.default-rule: &default-rule
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: never

.only-run-in-master: &only-run-in-master
  - if: $MANUAL_JOB == null && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - when: never

cocos-release:
  stage: release
  tags:
    - $LINUX_RUNNER_TAG
  image: registry.gitlab.com/inspirelab/greyhole/cicd/cicd-mono-go18:1.0
  rules: *only-run-in-master
  script:
    - echo "Run $CI_JOB_NAME"
    - echo $SCRIPT_DIR
    - $SCRIPT_DIR/release-cocos.sh

.cocos-build:
  stage: test
  tags:
    - $MACOS_RUNNER_TAG
  needs: []
  variables:
  before_script:
    - export NODE_PATH="/Users/helpercmgp/.nvm/versions/node/v12.20.1"
    - export PATH="$PATH:$NODE_PATH/bin"
    #- brew install gnu-sed
    - export SERVICE=$(echo $CI_COMMIT_TAG | gsed -re "s/^v([0-9]+.[0-9]+.[0-9]+)-([a-zA-Z0-9-]+)-[a-fA-F0-9]+/\2/" )
    - export VERSION=$(echo $CI_COMMIT_TAG | gsed -re "s/^v([0-9]+.[0-9]+.[0-9]+)-([a-zA-Z0-9-]+)-[a-fA-F0-9]+/\1/" )
  script:
    - $SCRIPT_DIR/build-cocos-with-notify.sh || true

.cocos-build-web:
  extends: .cocos-build
  variables:
    PLATFORM: web
  artifacts:
    when: always
    paths:
      - build.log
      - CHANGE_LOG
      - $CI_PROJECT_DIR/cocos/build/
    expire_in: 7 day
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /cocos-web/
      when: manual
    - when: never

web-dev-cocos:
  extends: .cocos-build-web
  stage: build
  variables:
    S3_BUCKET: "s3://carem-outsource-rlgl-dev"
    ENV: dev

web-stg-cocos:
  extends: .cocos-build-web
  stage: build
  variables:
    S3_BUCKET: "s3://carem-outsource-rlgl-stg"
    ENV: stg

upload-web-dev-cocos:
  stage: upload
  tags:
    - $LINUX_RUNNER_TAG
  image: 
    name: amazon/aws-cli:2.4.11
    entrypoint: [""]
  needs:
    - job: web-dev-cocos
      artifacts: true
  script:
    - aws s3 rm --recursive  s3://carem-outsource-rlgl-dev
    - aws s3 cp --recursive cocos/build/web-mobile s3://carem-outsource-rlgl-dev
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /cocos-web/
      when: manual
    - when: never

upload-web-stg-cocos:
  stage: upload
  tags:
    - $LINUX_RUNNER_TAG
  image: 
    name: amazon/aws-cli:2.4.11
    entrypoint: [""]
  needs:
    - job: web-dev-cocos
      artifacts: true
  script:
    - aws s3 rm --recursive  s3://carem-outsource-rlgl-stg
    - aws s3 cp --recursive cocos/build/web-mobile s3://carem-outsource-rlgl-stg
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /cocos-web/
      when: manual
    - when: never
